Repository Permify/permify, pull requests merged in 2023-02, with the labels that each got.

#207 open telemetry version upgrade
  internal/commands/check.go
  internal/repositories/postgres/relationshipWriter.go
  playground/src/services/s3.js
Labels: dependencies

#208 documantation dependabot updates
  .github/dependabot.yml
Labels: dependencies

#234 🔑 multi tenant authentication support (with jwt) added
  go.mod
  go.sum
  internal/authn/error.go
  internal/authn/multitenant/authn.go
  internal/authn/multitenant/interceptors.go
  internal/authn/preshared/authn.go
  internal/config/config.go
  internal/servers/middleware/authn.go
  internal/servers/server.go
  pkg/pb/base/v1/errors.pb.go
  proto/base/v1/errors.proto
Labels: feature request

#246 ✨ customizable cache configuration added
  example.config.yaml
  internal/config/config.go
  pkg/cache/interfaces.go
  pkg/cache/ristretto/consts.go
  pkg/cache/ristretto/options.go
  pkg/cache/ristretto/ristretto.go
  pkg/cmd/flags/serve.go
  pkg/cmd/serve.go
Labels: iteration

#256 fix: welcomeServer duplicated syntax
  internal/servers/welcomeServer.go
Labels: bug
