Repository Permify/permify, pull requests merged in 2024-02, with the labels that each got.

#1052 fix: typos on documentation homepage
  docs/docs/permify-overview/intro.md
  docs/versioned_docs/version-0.5.x/permify-overview/intro.md
  docs/versioned_docs/version-0.6.x/permify-overview/intro.md
Labels: documentation

#1053 chore: add air support for hot reloading
  .air.toml
  .gitignore
  Dockerfile.local
  Makefile
  docker-compose.yaml
Labels: docker

#1084 docs: added list schema and read schema api
  docs/docs/api-overview/schema/list-schema.md
  docs/docs/api-overview/schema/read-schema.md
Labels: documentation

#1097 fix: #1092
  pkg/cmd/serve.go
Labels: 🙋 Bounty claim
